#!/usr/bin/perl

use strict;
use warnings;

my $file = shift || exit;

for (@ARGV) {
    open( STDIN, '<', $file ) || die $!;
    while (<>) {
        $_{$_} = 1;
    }
    close STDIN;
}

open( STDIN, '<', $file ) || die $!;
while (<>) {
    print unless $_{$_};
}
close STDIN;
